##############################################################################
# loadCredentials role metadata
#
# Copyright 2025 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.0
# Date: January 02, 2026
##############################################################################

---                                            # identifies a YAML config file

dependencies:
  - role: common
