##############################################################################
# Ansible role dependencies for trustInternalCA
#
# Copyright 2026 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.0
# Date: May 7, 2026
##############################################################################

---

dependencies:
  - role: common