##############################################################################
# Role dependencies for getTargetHostIP role
#
# Copyright 2026 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.0
# Date: April 16, 2026
##############################################################################

---
dependencies:
  - role: common