##############################################################################
# Pretty display wrapper for ansibleRunner.
#
# USAGE:
#   - ansible.builtin.include_tasks:
#       file: "{{ taskPath }}/ui/niceDisplay.yaml"
#     vars:
#       title: "Sample output"
#       data: "preformatted text"
#
# Copyright 2026 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
##############################################################################
---
- name: "niceDisplay: {{ title | default('Default Title') }}"
  ansible.builtin.debug:
    msg: "{{ data }}"
