##############################################################################
# Ansible role dependencies for createUsers
#
# Copyright 2026 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.1
# Date: April 18, 2026
##############################################################################
---

dependencies:
  - role: common
