##############################################################################
# Ansible role to pause workflow and wait for user input
#
# This role wraps tasks/misc/waitForInput.yaml
# See that file for complete documentation and usage examples.
#
# Copyright 2025 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.2
# Date: October 16, 2025
##############################################################################

---                                            # identifies a YAML config file

##############################################################################
# Wait for input
##############################################################################
- name: wait of input to continue
  include_tasks:
    file: "{{ taskDir }}/misc/waitForInput.yaml"
